name: nexust
description: "Nexust es una herramienta poderosa diseñada para desarrolladores, testers y entusiastas de las APIs que buscan una alternativa moderna, rápida y multiplataforma para probar y documentar sus servicios REST."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^15.1.1

dependency_overrides:
  font_awesome_flutter:
    path: "lib/font_awesome_flutter"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
