// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfl6Qs3WChxVOqVES0XHo6XBSamKmvsfg',
    appId: '1:431032862826:web:140874699eca7ad25be213',
    messagingSenderId: '431032862826',
    projectId: 'nexust',
    authDomain: 'nexust.firebaseapp.com',
    storageBucket: 'nexust.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXGyQpAh9YUKQnQVovTWgb43ztYqptH5Y',
    appId: '1:431032862826:android:b2181e897f9d453c5be213',
    messagingSenderId: '431032862826',
    projectId: 'nexust',
    storageBucket: 'nexust.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfXwvCaykwahAFZ73dcS6YTSfT7D6_Xvk',
    appId: '1:431032862826:ios:7281285fcba79abf5be213',
    messagingSenderId: '431032862826',
    projectId: 'nexust',
    storageBucket: 'nexust.firebasestorage.app',
    androidClientId: '431032862826-g9l3g02rhake8rpuv99bu4r8aiua0hj2.apps.googleusercontent.com',
    iosClientId: '431032862826-e54vp3dsavhaeokka2l0k5r9mg223cs5.apps.googleusercontent.com',
    iosBundleId: 'com.axolotlsoftware.nexust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfXwvCaykwahAFZ73dcS6YTSfT7D6_Xvk',
    appId: '1:431032862826:ios:7281285fcba79abf5be213',
    messagingSenderId: '431032862826',
    projectId: 'nexust',
    storageBucket: 'nexust.firebasestorage.app',
    androidClientId: '431032862826-g9l3g02rhake8rpuv99bu4r8aiua0hj2.apps.googleusercontent.com',
    iosClientId: '431032862826-e54vp3dsavhaeokka2l0k5r9mg223cs5.apps.googleusercontent.com',
    iosBundleId: 'com.axolotlsoftware.nexust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfl6Qs3WChxVOqVES0XHo6XBSamKmvsfg',
    appId: '1:431032862826:web:682227524211ada75be213',
    messagingSenderId: '431032862826',
    projectId: 'nexust',
    authDomain: 'nexust.firebaseapp.com',
    storageBucket: 'nexust.firebasestorage.app',
  );
}
