name: Flutter CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test test/unit/ --coverage
